coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 2%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "dist/**/*"
  - "playwright-report/**/*"
  - "test-results/**/*"
  - "coverage/**/*"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/*.spec.ts"
  - "**/*.test.ts"